### ISSUE TITLE
Delete - Custome 404 Error

### ISSUE THREAD

**Issue by vaix-dungpx** [eliseekn/laravel-sanctum-starter-kit#1]
Hello, How can custome 404 Page

![image](https://github.com/eliseekn/laravel-sanctum-starter-kit/assets/114124789/77692796-37ac-4272-98e8-47e67959f274)

**Comment by eliseekn** [comment]
Hello! Thank you for using my package. I've made a new update based on your request. You can found an example of custom message error in the API routes for model not found. For example :

```php
Route::apiResource('users', UserController::class)->missing(function () {
    return response()->json([
        'status' => 'error',
        'message' => 'User not found',
    ], 404);
});
```
